application: plinko-poetry
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
#root
- url: /
  static_files: static/index.html
  upload: static/index.html

#serve our home page in case index.html is requested
- url: /index.html
  static_files: static/index.html
  upload: static/index.html

- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/img/logo.png
  upload: static/img/logo.png
 
- url: /favicon\.ico
  mime_type: image/png
  static_files: static/img/sm_logo.png
  upload: static/img/sm_logo.png
 
- url: /(robots\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|crossdomain\.xml)
 
- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  
- url: /swf/(.*\.swf)
  static_files: static/swf/\1
  upload: static/swf/(.*\.swf)
 
- url: /css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)
 
- url: /js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)
 
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
 
- url: /.*
  script: index.py


skip_files:
# Default patterns skipped by App Engine, which must be repeated since
# specifying skip_files overrides them otherwise.  See
# https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files.
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^.*\.pyc$

